//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAI_DONVI
    {
        public int ID { get; set; }
        public string LOAI { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<int> NGUOISUA { get; set; }
    }
}
