//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_THAOTAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_THAOTAC()
        {
            this.VAITRO_THAOTAC = new HashSet<VAITRO_THAOTAC>();
        }
    
        public long DM_THAOTAC_ID { get; set; }
        public string THAOTAC { get; set; }
        public string TEN_THAOTAC { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<int> DM_CHUCNANG_ID { get; set; }
        public string NGUOITAO { get; set; }
        public string NGUOISUA { get; set; }
        public string MENU_LINK { get; set; }
        public Nullable<bool> IS_SHOW { get; set; }
        public Nullable<int> TT_HIENTHI { get; set; }
        public Nullable<bool> IS_HIENTHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAITRO_THAOTAC> VAITRO_THAOTAC { get; set; }
    }
}
