//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_VAITRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_VAITRO()
        {
            this.VAITRO_CHUCNANG = new HashSet<VAITRO_CHUCNANG>();
        }
    
        public int DM_VAITRO_ID { get; set; }
        public string MA_VAITRO { get; set; }
        public string TEN_VAITRO { get; set; }
        public Nullable<int> COSO_ID { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public string NGUOITAO { get; set; }
        public string NGUOISUA { get; set; }
        public Nullable<int> CAPCOSO_ID { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAITRO_CHUCNANG> VAITRO_CHUCNANG { get; set; }
    }
}
