//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB_CHUKY
    {
        public long ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string CHUKY { get; set; }
        public Nullable<bool> IS_MAIN { get; set; }
    }
}
