//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUYEN
    {
        public long HUYEN_ID { get; set; }
        public string MAHUYEN { get; set; }
        public Nullable<int> TINH_ID { get; set; }
        public string TENHUYEN { get; set; }
        public string TYPE { get; set; }
        public string LOCATION { get; set; }
    }
}
