//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CCTC_THANHPHAN> CCTC_THANHPHAN { get; set; }
        public virtual DbSet<DM_CHUCNANG> DM_CHUCNANG { get; set; }
        public virtual DbSet<DM_LOAI_DONVI> DM_LOAI_DONVI { get; set; }
        public virtual DbSet<DM_NGUOIDUNG> DM_NGUOIDUNG { get; set; }
        public virtual DbSet<DM_THAOTAC> DM_THAOTAC { get; set; }
        public virtual DbSet<DM_VAITRO> DM_VAITRO { get; set; }
        public virtual DbSet<HUYEN> HUYEN { get; set; }
        public virtual DbSet<NGUOIDUNG_VAITRO> NGUOIDUNG_VAITRO { get; set; }
        public virtual DbSet<SPIN_BAIVIET> SPIN_BAIVIET { get; set; }
        public virtual DbSet<SPIN_BAIVIET_GROUP> SPIN_BAIVIET_GROUP { get; set; }
        public virtual DbSet<SPIN_CHUDE> SPIN_CHUDE { get; set; }
        public virtual DbSet<SPIN_GROUP_WORD> SPIN_GROUP_WORD { get; set; }
        public virtual DbSet<SPIN_WORDS> SPIN_WORDS { get; set; }
        public virtual DbSet<TAILIEUDINHKEM> TAILIEUDINHKEM { get; set; }
        public virtual DbSet<TBL_CONFIG_TAILIEU> TBL_CONFIG_TAILIEU { get; set; }
        public virtual DbSet<TBL_SOKETXUAT> TBL_SOKETXUAT { get; set; }
        public virtual DbSet<TBL_TAILIEU_KETXUAT> TBL_TAILIEU_KETXUAT { get; set; }
        public virtual DbSet<TINH> TINH { get; set; }
        public virtual DbSet<VAITRO_CHUCNANG> VAITRO_CHUCNANG { get; set; }
        public virtual DbSet<VAITRO_THAOTAC> VAITRO_THAOTAC { get; set; }
        public virtual DbSet<XA> XA { get; set; }
    }
}
