//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPIN_BAIVIET
    {
        public long ID { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> NGUOISUA { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<bool> IS_ORIGIN { get; set; }
        public long EXTEND_OF { get; set; }
    }
}
