//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPIN_WORDS
    {
        public long ID { get; set; }
        public string TU_CUMTU { get; set; }
        public Nullable<int> NHOMTU_ID { get; set; }
        public Nullable<int> CHUDE { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> NGUOITAO { get; set; }
    }
}
