//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAILIEUDINHKEM
    {
        public long TAILIEU_ID { get; set; }
        public Nullable<long> KICHCO { get; set; }
        public Nullable<System.DateTime> NGAYPHATHANH { get; set; }
        public string VERSION { get; set; }
        public string TENTACGIA { get; set; }
        public string MATAILIEU { get; set; }
        public string TENTAILIEU { get; set; }
        public Nullable<int> LOAI_TAILIEU { get; set; }
        public Nullable<long> ITEM_ID { get; set; }
        public string MOTA { get; set; }
        public string DUONGDAN_FILE { get; set; }
        public string DINHDANG_FILE { get; set; }
        public Nullable<int> SOLUONG_DOWNLOAD { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> FOLDER_ID { get; set; }
        public Nullable<int> IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> DM_LOAITAILIEU_ID { get; set; }
        public Nullable<bool> IS_LOCK { get; set; }
        public Nullable<long> NGUOI_LOCK { get; set; }
        public Nullable<bool> IS_QLPHIENBAN { get; set; }
        public Nullable<int> IS_PHEDUYET { get; set; }
        public Nullable<bool> IS_SHARING { get; set; }
        public Nullable<bool> IS_PRIVATE { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public string CONTENT_CHANGE { get; set; }
    }
}
