//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONFIG_TAILIEU
    {
        public long ID { get; set; }
        public Nullable<int> ID_TAILIEU { get; set; }
        public string FIELD_KEY { get; set; }
        public string FIELD_VALUE { get; set; }
        public string COLUM_MIX { get; set; }
    }
}
