//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TAILIEU_KETXUAT
    {
        public int ID { get; set; }
        public string TENTAILIEU { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<int> NGUOISUA { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string MA_TAILIEU { get; set; }
        public Nullable<int> SOTAILIEU { get; set; }
    }
}
