//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINH
    {
        public int TINH_ID { get; set; }
        public string MATINH { get; set; }
        public string TENTINH { get; set; }
        public string TYPE { get; set; }
    }
}
