//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAITRO_THAOTAC
    {
        public int VAITRO_THAOTAC_ID { get; set; }
        public Nullable<long> DM_THAOTAC_ID { get; set; }
        public Nullable<int> VAITRO_CHUCNANG_ID { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public string NGUOITAO { get; set; }
        public string NGUOISUA { get; set; }
        public Nullable<int> COSO_ID { get; set; }
    
        public virtual DM_THAOTAC DM_THAOTAC { get; set; }
        public virtual VAITRO_CHUCNANG VAITRO_CHUCNANG { get; set; }
    }
}
