//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAITRO_CHUCNANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VAITRO_CHUCNANG()
        {
            this.VAITRO_THAOTAC = new HashSet<VAITRO_THAOTAC>();
        }
    
        public int VAITRO_CHUCNANG_ID { get; set; }
        public Nullable<int> DM_CHUCNANG_ID { get; set; }
        public Nullable<int> DM_VAITRO_ID { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public string NGUOITAO { get; set; }
        public string NGUOISUA { get; set; }
        public Nullable<int> MAC_DINH { get; set; }
        public Nullable<int> COSO_ID { get; set; }
    
        public virtual DM_CHUCNANG DM_CHUCNANG { get; set; }
        public virtual DM_VAITRO DM_VAITRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAITRO_THAOTAC> VAITRO_THAOTAC { get; set; }
    }
}
