//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Web.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsBulkSmsPortBinding", Namespace="http://impl.bulkSms.ws/")]
    public partial class WSBulkSms : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback checkBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsCpMtOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsCpMtTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsCpCtntOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsReportHourOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsReportDailyOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsReportMonthOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSBulkSms() {
            this.Url = global::Web.Properties.Settings.Default.Web_WebReference_WSBulkSms;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event checkBalanceCompletedEventHandler checkBalanceCompleted;
        
        /// <remarks/>
        public event wsCpMtCompletedEventHandler wsCpMtCompleted;
        
        /// <remarks/>
        public event wsCpMtTestCompletedEventHandler wsCpMtTestCompleted;
        
        /// <remarks/>
        public event wsCpCtntCompletedEventHandler wsCpCtntCompleted;
        
        /// <remarks/>
        public event wsReportHourCompletedEventHandler wsReportHourCompleted;
        
        /// <remarks/>
        public event wsReportDailyCompletedEventHandler wsReportDailyCompleted;
        
        /// <remarks/>
        public event wsReportMonthCompletedEventHandler wsReportMonthCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.bulkSms.ws/", ResponseNamespace="http://impl.bulkSms.ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cpBalance checkBalance([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string User, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CPCode) {
            object[] results = this.Invoke("checkBalance", new object[] {
                        User,
                        Password,
                        CPCode});
            return ((cpBalance)(results[0]));
        }
        
        /// <remarks/>
        public void checkBalanceAsync(string User, string Password, string CPCode) {
            this.checkBalanceAsync(User, Password, CPCode, null);
        }
        
        /// <remarks/>
        public void checkBalanceAsync(string User, string Password, string CPCode, object userState) {
            if ((this.checkBalanceOperationCompleted == null)) {
                this.checkBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckBalanceOperationCompleted);
            }
            this.InvokeAsync("checkBalance", new object[] {
                        User,
                        Password,
                        CPCode}, this.checkBalanceOperationCompleted, userState);
        }
        
        private void OncheckBalanceOperationCompleted(object arg) {
            if ((this.checkBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkBalanceCompleted(this, new checkBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.bulkSms.ws/", ResponseNamespace="http://impl.bulkSms.ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultBO wsCpMt([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string User, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CPCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string RequestID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string UserID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ReceiverID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ServiceID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CommandCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Content, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ContentType) {
            object[] results = this.Invoke("wsCpMt", new object[] {
                        User,
                        Password,
                        CPCode,
                        RequestID,
                        UserID,
                        ReceiverID,
                        ServiceID,
                        CommandCode,
                        Content,
                        ContentType});
            return ((resultBO)(results[0]));
        }
        
        /// <remarks/>
        public void wsCpMtAsync(string User, string Password, string CPCode, string RequestID, string UserID, string ReceiverID, string ServiceID, string CommandCode, string Content, string ContentType) {
            this.wsCpMtAsync(User, Password, CPCode, RequestID, UserID, ReceiverID, ServiceID, CommandCode, Content, ContentType, null);
        }
        
        /// <remarks/>
        public void wsCpMtAsync(string User, string Password, string CPCode, string RequestID, string UserID, string ReceiverID, string ServiceID, string CommandCode, string Content, string ContentType, object userState) {
            if ((this.wsCpMtOperationCompleted == null)) {
                this.wsCpMtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsCpMtOperationCompleted);
            }
            this.InvokeAsync("wsCpMt", new object[] {
                        User,
                        Password,
                        CPCode,
                        RequestID,
                        UserID,
                        ReceiverID,
                        ServiceID,
                        CommandCode,
                        Content,
                        ContentType}, this.wsCpMtOperationCompleted, userState);
        }
        
        private void OnwsCpMtOperationCompleted(object arg) {
            if ((this.wsCpMtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsCpMtCompleted(this, new wsCpMtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.bulkSms.ws/", ResponseNamespace="http://impl.bulkSms.ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultBO wsCpMtTest([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string User, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CPCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string RequestID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string UserID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ReceiverID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ServiceID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CommandCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Content, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ContentType) {
            object[] results = this.Invoke("wsCpMtTest", new object[] {
                        User,
                        Password,
                        CPCode,
                        RequestID,
                        UserID,
                        ReceiverID,
                        ServiceID,
                        CommandCode,
                        Content,
                        ContentType});
            return ((resultBO)(results[0]));
        }
        
        /// <remarks/>
        public void wsCpMtTestAsync(string User, string Password, string CPCode, string RequestID, string UserID, string ReceiverID, string ServiceID, string CommandCode, string Content, string ContentType) {
            this.wsCpMtTestAsync(User, Password, CPCode, RequestID, UserID, ReceiverID, ServiceID, CommandCode, Content, ContentType, null);
        }
        
        /// <remarks/>
        public void wsCpMtTestAsync(string User, string Password, string CPCode, string RequestID, string UserID, string ReceiverID, string ServiceID, string CommandCode, string Content, string ContentType, object userState) {
            if ((this.wsCpMtTestOperationCompleted == null)) {
                this.wsCpMtTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsCpMtTestOperationCompleted);
            }
            this.InvokeAsync("wsCpMtTest", new object[] {
                        User,
                        Password,
                        CPCode,
                        RequestID,
                        UserID,
                        ReceiverID,
                        ServiceID,
                        CommandCode,
                        Content,
                        ContentType}, this.wsCpMtTestOperationCompleted, userState);
        }
        
        private void OnwsCpMtTestOperationCompleted(object arg) {
            if ((this.wsCpMtTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsCpMtTestCompleted(this, new wsCpMtTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.bulkSms.ws/", ResponseNamespace="http://impl.bulkSms.ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultBO wsCpCtnt([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string User, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CPCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ProgCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Alias, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Content, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ReceiverID) {
            object[] results = this.Invoke("wsCpCtnt", new object[] {
                        User,
                        Password,
                        CPCode,
                        ProgCode,
                        Alias,
                        Content,
                        ReceiverID});
            return ((resultBO)(results[0]));
        }
        
        /// <remarks/>
        public void wsCpCtntAsync(string User, string Password, string CPCode, string ProgCode, string Alias, string Content, string ReceiverID) {
            this.wsCpCtntAsync(User, Password, CPCode, ProgCode, Alias, Content, ReceiverID, null);
        }
        
        /// <remarks/>
        public void wsCpCtntAsync(string User, string Password, string CPCode, string ProgCode, string Alias, string Content, string ReceiverID, object userState) {
            if ((this.wsCpCtntOperationCompleted == null)) {
                this.wsCpCtntOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsCpCtntOperationCompleted);
            }
            this.InvokeAsync("wsCpCtnt", new object[] {
                        User,
                        Password,
                        CPCode,
                        ProgCode,
                        Alias,
                        Content,
                        ReceiverID}, this.wsCpCtntOperationCompleted, userState);
        }
        
        private void OnwsCpCtntOperationCompleted(object arg) {
            if ((this.wsCpCtntCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsCpCtntCompleted(this, new wsCpCtntCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.bulkSms.ws/", ResponseNamespace="http://impl.bulkSms.ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public reportHourBO[] wsReportHour([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string User, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CPCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string timeReport) {
            object[] results = this.Invoke("wsReportHour", new object[] {
                        User,
                        Password,
                        CPCode,
                        timeReport});
            return ((reportHourBO[])(results[0]));
        }
        
        /// <remarks/>
        public void wsReportHourAsync(string User, string Password, string CPCode, string timeReport) {
            this.wsReportHourAsync(User, Password, CPCode, timeReport, null);
        }
        
        /// <remarks/>
        public void wsReportHourAsync(string User, string Password, string CPCode, string timeReport, object userState) {
            if ((this.wsReportHourOperationCompleted == null)) {
                this.wsReportHourOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsReportHourOperationCompleted);
            }
            this.InvokeAsync("wsReportHour", new object[] {
                        User,
                        Password,
                        CPCode,
                        timeReport}, this.wsReportHourOperationCompleted, userState);
        }
        
        private void OnwsReportHourOperationCompleted(object arg) {
            if ((this.wsReportHourCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsReportHourCompleted(this, new wsReportHourCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.bulkSms.ws/", ResponseNamespace="http://impl.bulkSms.ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public reportDailyBO[] wsReportDaily([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string User, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CPCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string startDate, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string endDate) {
            object[] results = this.Invoke("wsReportDaily", new object[] {
                        User,
                        Password,
                        CPCode,
                        startDate,
                        endDate});
            return ((reportDailyBO[])(results[0]));
        }
        
        /// <remarks/>
        public void wsReportDailyAsync(string User, string Password, string CPCode, string startDate, string endDate) {
            this.wsReportDailyAsync(User, Password, CPCode, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void wsReportDailyAsync(string User, string Password, string CPCode, string startDate, string endDate, object userState) {
            if ((this.wsReportDailyOperationCompleted == null)) {
                this.wsReportDailyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsReportDailyOperationCompleted);
            }
            this.InvokeAsync("wsReportDaily", new object[] {
                        User,
                        Password,
                        CPCode,
                        startDate,
                        endDate}, this.wsReportDailyOperationCompleted, userState);
        }
        
        private void OnwsReportDailyOperationCompleted(object arg) {
            if ((this.wsReportDailyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsReportDailyCompleted(this, new wsReportDailyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.bulkSms.ws/", ResponseNamespace="http://impl.bulkSms.ws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public reportMonthBO[] wsReportMonth([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string User, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CPCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string startMonth, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string endMonth) {
            object[] results = this.Invoke("wsReportMonth", new object[] {
                        User,
                        Password,
                        CPCode,
                        startMonth,
                        endMonth});
            return ((reportMonthBO[])(results[0]));
        }
        
        /// <remarks/>
        public void wsReportMonthAsync(string User, string Password, string CPCode, string startMonth, string endMonth) {
            this.wsReportMonthAsync(User, Password, CPCode, startMonth, endMonth, null);
        }
        
        /// <remarks/>
        public void wsReportMonthAsync(string User, string Password, string CPCode, string startMonth, string endMonth, object userState) {
            if ((this.wsReportMonthOperationCompleted == null)) {
                this.wsReportMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsReportMonthOperationCompleted);
            }
            this.InvokeAsync("wsReportMonth", new object[] {
                        User,
                        Password,
                        CPCode,
                        startMonth,
                        endMonth}, this.wsReportMonthOperationCompleted, userState);
        }
        
        private void OnwsReportMonthOperationCompleted(object arg) {
            if ((this.wsReportMonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsReportMonthCompleted(this, new wsReportMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bulk.viettel.com.vn/")]
    public partial class cpBalance {
        
        private long balanceField;
        
        private int errCodeField;
        
        private string errDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.bulkSms.ws/")]
    public partial class reportMonthBO {
        
        private string cpAliasField;
        
        private string cpCodeField;
        
        private long cpIdField;
        
        private bool cpIdFieldSpecified;
        
        private string messageField;
        
        private long mtErrorField;
        
        private bool mtErrorFieldSpecified;
        
        private long mtErrorAliasField;
        
        private bool mtErrorAliasFieldSpecified;
        
        private long mtFailureField;
        
        private bool mtFailureFieldSpecified;
        
        private long mtSentField;
        
        private bool mtSentFieldSpecified;
        
        private long mtSentOutField;
        
        private bool mtSentOutFieldSpecified;
        
        private long mtSentVtField;
        
        private bool mtSentVtFieldSpecified;
        
        private string reportMonthField;
        
        private long reportMonthIdField;
        
        private bool reportMonthIdFieldSpecified;
        
        private long resultField;
        
        private bool resultFieldSpecified;
        
        private long smsSentField;
        
        private bool smsSentFieldSpecified;
        
        private long smsSentOutField;
        
        private bool smsSentOutFieldSpecified;
        
        private long smsSentVtField;
        
        private bool smsSentVtFieldSpecified;
        
        private long sumMTField;
        
        private bool sumMTFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpAlias {
            get {
                return this.cpAliasField;
            }
            set {
                this.cpAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpCode {
            get {
                return this.cpCodeField;
            }
            set {
                this.cpCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cpId {
            get {
                return this.cpIdField;
            }
            set {
                this.cpIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cpIdSpecified {
            get {
                return this.cpIdFieldSpecified;
            }
            set {
                this.cpIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtError {
            get {
                return this.mtErrorField;
            }
            set {
                this.mtErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtErrorSpecified {
            get {
                return this.mtErrorFieldSpecified;
            }
            set {
                this.mtErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtErrorAlias {
            get {
                return this.mtErrorAliasField;
            }
            set {
                this.mtErrorAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtErrorAliasSpecified {
            get {
                return this.mtErrorAliasFieldSpecified;
            }
            set {
                this.mtErrorAliasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtFailure {
            get {
                return this.mtFailureField;
            }
            set {
                this.mtFailureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtFailureSpecified {
            get {
                return this.mtFailureFieldSpecified;
            }
            set {
                this.mtFailureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtSent {
            get {
                return this.mtSentField;
            }
            set {
                this.mtSentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtSentSpecified {
            get {
                return this.mtSentFieldSpecified;
            }
            set {
                this.mtSentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtSentOut {
            get {
                return this.mtSentOutField;
            }
            set {
                this.mtSentOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtSentOutSpecified {
            get {
                return this.mtSentOutFieldSpecified;
            }
            set {
                this.mtSentOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtSentVt {
            get {
                return this.mtSentVtField;
            }
            set {
                this.mtSentVtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtSentVtSpecified {
            get {
                return this.mtSentVtFieldSpecified;
            }
            set {
                this.mtSentVtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportMonth {
            get {
                return this.reportMonthField;
            }
            set {
                this.reportMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long reportMonthId {
            get {
                return this.reportMonthIdField;
            }
            set {
                this.reportMonthIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reportMonthIdSpecified {
            get {
                return this.reportMonthIdFieldSpecified;
            }
            set {
                this.reportMonthIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultSpecified {
            get {
                return this.resultFieldSpecified;
            }
            set {
                this.resultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long smsSent {
            get {
                return this.smsSentField;
            }
            set {
                this.smsSentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsSentSpecified {
            get {
                return this.smsSentFieldSpecified;
            }
            set {
                this.smsSentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long smsSentOut {
            get {
                return this.smsSentOutField;
            }
            set {
                this.smsSentOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsSentOutSpecified {
            get {
                return this.smsSentOutFieldSpecified;
            }
            set {
                this.smsSentOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long smsSentVt {
            get {
                return this.smsSentVtField;
            }
            set {
                this.smsSentVtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsSentVtSpecified {
            get {
                return this.smsSentVtFieldSpecified;
            }
            set {
                this.smsSentVtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sumMT {
            get {
                return this.sumMTField;
            }
            set {
                this.sumMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumMTSpecified {
            get {
                return this.sumMTFieldSpecified;
            }
            set {
                this.sumMTFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.bulkSms.ws/")]
    public partial class reportDailyBO {
        
        private string cpAliasField;
        
        private string cpCodeField;
        
        private long cpIdField;
        
        private bool cpIdFieldSpecified;
        
        private string messageField;
        
        private long mtErrorField;
        
        private bool mtErrorFieldSpecified;
        
        private long mtErrorAliasField;
        
        private bool mtErrorAliasFieldSpecified;
        
        private long mtFailureField;
        
        private bool mtFailureFieldSpecified;
        
        private long mtSentField;
        
        private bool mtSentFieldSpecified;
        
        private long mtSentOutField;
        
        private bool mtSentOutFieldSpecified;
        
        private long mtSentVtField;
        
        private bool mtSentVtFieldSpecified;
        
        private long reportDailyIdField;
        
        private bool reportDailyIdFieldSpecified;
        
        private string reportDateField;
        
        private long resultField;
        
        private bool resultFieldSpecified;
        
        private long smsSentField;
        
        private bool smsSentFieldSpecified;
        
        private long smsSentOutField;
        
        private bool smsSentOutFieldSpecified;
        
        private long smsSentVtField;
        
        private bool smsSentVtFieldSpecified;
        
        private long sumMTField;
        
        private bool sumMTFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpAlias {
            get {
                return this.cpAliasField;
            }
            set {
                this.cpAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpCode {
            get {
                return this.cpCodeField;
            }
            set {
                this.cpCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cpId {
            get {
                return this.cpIdField;
            }
            set {
                this.cpIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cpIdSpecified {
            get {
                return this.cpIdFieldSpecified;
            }
            set {
                this.cpIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtError {
            get {
                return this.mtErrorField;
            }
            set {
                this.mtErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtErrorSpecified {
            get {
                return this.mtErrorFieldSpecified;
            }
            set {
                this.mtErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtErrorAlias {
            get {
                return this.mtErrorAliasField;
            }
            set {
                this.mtErrorAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtErrorAliasSpecified {
            get {
                return this.mtErrorAliasFieldSpecified;
            }
            set {
                this.mtErrorAliasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtFailure {
            get {
                return this.mtFailureField;
            }
            set {
                this.mtFailureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtFailureSpecified {
            get {
                return this.mtFailureFieldSpecified;
            }
            set {
                this.mtFailureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtSent {
            get {
                return this.mtSentField;
            }
            set {
                this.mtSentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtSentSpecified {
            get {
                return this.mtSentFieldSpecified;
            }
            set {
                this.mtSentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtSentOut {
            get {
                return this.mtSentOutField;
            }
            set {
                this.mtSentOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtSentOutSpecified {
            get {
                return this.mtSentOutFieldSpecified;
            }
            set {
                this.mtSentOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtSentVt {
            get {
                return this.mtSentVtField;
            }
            set {
                this.mtSentVtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtSentVtSpecified {
            get {
                return this.mtSentVtFieldSpecified;
            }
            set {
                this.mtSentVtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long reportDailyId {
            get {
                return this.reportDailyIdField;
            }
            set {
                this.reportDailyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reportDailyIdSpecified {
            get {
                return this.reportDailyIdFieldSpecified;
            }
            set {
                this.reportDailyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportDate {
            get {
                return this.reportDateField;
            }
            set {
                this.reportDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultSpecified {
            get {
                return this.resultFieldSpecified;
            }
            set {
                this.resultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long smsSent {
            get {
                return this.smsSentField;
            }
            set {
                this.smsSentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsSentSpecified {
            get {
                return this.smsSentFieldSpecified;
            }
            set {
                this.smsSentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long smsSentOut {
            get {
                return this.smsSentOutField;
            }
            set {
                this.smsSentOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsSentOutSpecified {
            get {
                return this.smsSentOutFieldSpecified;
            }
            set {
                this.smsSentOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long smsSentVt {
            get {
                return this.smsSentVtField;
            }
            set {
                this.smsSentVtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsSentVtSpecified {
            get {
                return this.smsSentVtFieldSpecified;
            }
            set {
                this.smsSentVtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sumMT {
            get {
                return this.sumMTField;
            }
            set {
                this.sumMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumMTSpecified {
            get {
                return this.sumMTFieldSpecified;
            }
            set {
                this.sumMTFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.bulkSms.ws/")]
    public partial class reportHourBO {
        
        private string cpAliasField;
        
        private string cpCodeField;
        
        private long cpIdField;
        
        private bool cpIdFieldSpecified;
        
        private string messageField;
        
        private long mtErrorField;
        
        private bool mtErrorFieldSpecified;
        
        private long mtErrorAliasField;
        
        private bool mtErrorAliasFieldSpecified;
        
        private long mtFailureField;
        
        private bool mtFailureFieldSpecified;
        
        private long mtSentField;
        
        private bool mtSentFieldSpecified;
        
        private long mtSentOutField;
        
        private bool mtSentOutFieldSpecified;
        
        private long mtSentVtField;
        
        private bool mtSentVtFieldSpecified;
        
        private string reportHourField;
        
        private long reportHourIdField;
        
        private bool reportHourIdFieldSpecified;
        
        private long resultField;
        
        private bool resultFieldSpecified;
        
        private long smsSentField;
        
        private bool smsSentFieldSpecified;
        
        private long smsSentOutField;
        
        private bool smsSentOutFieldSpecified;
        
        private long smsSentVtField;
        
        private bool smsSentVtFieldSpecified;
        
        private long sumMTField;
        
        private bool sumMTFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpAlias {
            get {
                return this.cpAliasField;
            }
            set {
                this.cpAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpCode {
            get {
                return this.cpCodeField;
            }
            set {
                this.cpCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cpId {
            get {
                return this.cpIdField;
            }
            set {
                this.cpIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cpIdSpecified {
            get {
                return this.cpIdFieldSpecified;
            }
            set {
                this.cpIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtError {
            get {
                return this.mtErrorField;
            }
            set {
                this.mtErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtErrorSpecified {
            get {
                return this.mtErrorFieldSpecified;
            }
            set {
                this.mtErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtErrorAlias {
            get {
                return this.mtErrorAliasField;
            }
            set {
                this.mtErrorAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtErrorAliasSpecified {
            get {
                return this.mtErrorAliasFieldSpecified;
            }
            set {
                this.mtErrorAliasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtFailure {
            get {
                return this.mtFailureField;
            }
            set {
                this.mtFailureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtFailureSpecified {
            get {
                return this.mtFailureFieldSpecified;
            }
            set {
                this.mtFailureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtSent {
            get {
                return this.mtSentField;
            }
            set {
                this.mtSentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtSentSpecified {
            get {
                return this.mtSentFieldSpecified;
            }
            set {
                this.mtSentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtSentOut {
            get {
                return this.mtSentOutField;
            }
            set {
                this.mtSentOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtSentOutSpecified {
            get {
                return this.mtSentOutFieldSpecified;
            }
            set {
                this.mtSentOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mtSentVt {
            get {
                return this.mtSentVtField;
            }
            set {
                this.mtSentVtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtSentVtSpecified {
            get {
                return this.mtSentVtFieldSpecified;
            }
            set {
                this.mtSentVtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportHour {
            get {
                return this.reportHourField;
            }
            set {
                this.reportHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long reportHourId {
            get {
                return this.reportHourIdField;
            }
            set {
                this.reportHourIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reportHourIdSpecified {
            get {
                return this.reportHourIdFieldSpecified;
            }
            set {
                this.reportHourIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultSpecified {
            get {
                return this.resultFieldSpecified;
            }
            set {
                this.resultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long smsSent {
            get {
                return this.smsSentField;
            }
            set {
                this.smsSentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsSentSpecified {
            get {
                return this.smsSentFieldSpecified;
            }
            set {
                this.smsSentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long smsSentOut {
            get {
                return this.smsSentOutField;
            }
            set {
                this.smsSentOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsSentOutSpecified {
            get {
                return this.smsSentOutFieldSpecified;
            }
            set {
                this.smsSentOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long smsSentVt {
            get {
                return this.smsSentVtField;
            }
            set {
                this.smsSentVtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsSentVtSpecified {
            get {
                return this.smsSentVtFieldSpecified;
            }
            set {
                this.smsSentVtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sumMT {
            get {
                return this.sumMTField;
            }
            set {
                this.sumMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumMTSpecified {
            get {
                return this.sumMTFieldSpecified;
            }
            set {
                this.sumMTFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.bulkSms.ws/")]
    public partial class resultBO {
        
        private string messageField;
        
        private long resultField;
        
        private bool resultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultSpecified {
            get {
                return this.resultFieldSpecified;
            }
            set {
                this.resultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void checkBalanceCompletedEventHandler(object sender, checkBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cpBalance Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cpBalance)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void wsCpMtCompletedEventHandler(object sender, wsCpMtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsCpMtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsCpMtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultBO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultBO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void wsCpMtTestCompletedEventHandler(object sender, wsCpMtTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsCpMtTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsCpMtTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultBO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultBO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void wsCpCtntCompletedEventHandler(object sender, wsCpCtntCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsCpCtntCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsCpCtntCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultBO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultBO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void wsReportHourCompletedEventHandler(object sender, wsReportHourCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsReportHourCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsReportHourCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public reportHourBO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((reportHourBO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void wsReportDailyCompletedEventHandler(object sender, wsReportDailyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsReportDailyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsReportDailyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public reportDailyBO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((reportDailyBO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void wsReportMonthCompletedEventHandler(object sender, wsReportMonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsReportMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsReportMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public reportMonthBO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((reportMonthBO[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591